### ISSUE TITLE
Feature request: supporting billions of rows, all scrollable

### ISSUE THREAD

**Issue by benkeen** [bvaughn/react-window-infinite-loader#31]
This is a *would-you-like-this-feature?-if-so-I'll-put-in-a-PR* feature request. I just wanted to sound you out about it first.

We have a specific need for a single scrollable list that can support any number of rows, say a billion or more. `react-window` in combination with this repo is marvellous, but it doesn't quite fit our needs. Our UX team have insisted on a specific behaviour: the scrollable region should encompass the entire data set, regardless of size. So unlike the demos in this repo, right off the bat when you show the list, the scrollbar would appear with the correct height for all **N** possible rows and users could drag the scrollbar from the top to the bottom to see, say, the final billionth row. (Obviously the row data is loaded async).

I was able to get this working for smaller data sets (1.5 million rows or so) using this lib & react-window, but at the 2 million mark I ran into a hard limit in the browser. Browsers have a max DOM element size: with Chrome it's about 33.7 million - other browsers are less. So because the library works by creating a single DOM element with the correct height for all rows it hits that limit.

Curses! 

So... researching this a bit further, I found a solution for SlickGrid that was rather sneaky. See here for a demo: http://jsfiddle.net/SDa2B/4/

What that does is circumvent browser limitations by overriding the scroll behaviour. The total height of the scrollable region is only ever as high as a browser can handle, but as you scroll it does some math to adjust the exact position of the visible rows, cramming more rows than possible into the region. It's a little hard to explain and requires some face-scrunching when examining the math but it makes sense. The downside to this approach is a slight jumpiness in the scrollbar as you're scrolling slowly as it re-paints the rows at a slightly different absolute position. But to accommodate such a feature, our UX team have given it the thumbs up. For such large data sets, the scrollbar jumping is quite minimal. For sizes less than the possible DOM element size, there's no jumpiness at all. 

Would there be any interesting incorporating such a solution into this lib or react-window? We can always roll our own component (actually I already got a proof-of-concept going in React) but we'd far rather contribute this back & get all the benefits of your awesome libs.

Thanks!

**Comment by bvaughn** [comment]
This is a long and thoughtfully written issue, so thank you. Unfortunately I am swamped at the moment preparing for my React conf talk, so I'm going to have to leave a brief response. I hope you'll understand.

The short answer is: I don't want to add something like this to react-window, because I don't think showing "billions of rows" (or even millions) is a good user experience. It's too much data. Loading so much data- let alone scrolling around in it- is not user friendly.

My previous virtualization library, react-virtualized, did this same type of compression. (I actually gave [a talk about it](https://bvaughn.github.io/connect-tech-2016/#/23/5) a few years ago at Connect Tech.) In addition to adding some complexity to the code, it also made scrolling feel weirder the larger the data gets (because of the more compression it required).

This has come up before from time to time (https://github.com/bvaughn/react-window/issues/108#issuecomment-447489217) but my stance on it has been that it's something I'm intentionally _not_ supporting, for the reasons mentioned above.

Thanks and I hope you understand!

**Comment by benkeen** [comment]
No worries, I should have figured that this issue had come up before, I appreciate the info. And best of luck with the React conf talk!
