### ISSUE TITLE
I'm not sure how to implement a list with reversed direction

### ISSUE THREAD

**Issue by everdimension** [bvaughn/react-window-infinite-loader#6]
What I mean is a list where you have to scroll up to load older items.

Is the idea to know how many items there are *in total* and then pretend that the items which are loaded have the indexes that they would have if I had *all* items loaded?

Not sure that's the best approach. What would you recommend? Is there a "reverse" prop somewhere?

**Comment by bvaughn** [comment]
> Is there a "reverse" prop somewhere?

There is no reverse prop. You will have to map index to items somehow. (Probably an Array is the easiest way to do this, and you can concat or splice things onto the beginning of the array.)

> Is the idea to know how many items there are _in total_ and then pretend that the items which are loaded have the indexes that they would have if I had _all_ items loaded?

This is a good way to do it, if you _can_ know the total amount of remote items, yes.

I'm going to close this issue because it's not really actionable. I hope my answers/confirmations have been somewhat helpful though!

**Comment by zackster** [comment]
@everdimension this seems like a pretty common use case, so if you managed to develop a solution, I would love to hear all the details.  For example, how you got it to trigger the loadNextPage event through scrolling upward.

**Comment by zackster** [comment]
I still don't know how to load my react-window widget scrolled to the very bottom 😞
