### ISSUE TITLE
Implement infinite scrolling using window scroll

### ISSUE THREAD

**Issue by roboli** [bvaughn/react-window-infinite-loader#9]
Hi, do you have an example on how to implement this? Thanks.

**Comment by bvaughn** [comment]
Hello! 😄 

For this type of question, I suggest using Stack Overflow. I try to keep issues focused on bug reports and feature-requests.

This helps keep the project somewhat more maintainable for me _and_ hopefully gets you an answer faster (since more people check those places than monitor GitHub issues). 😄
